spring:
  cloud:
    servicecomb:
      discovery:
        watch: false
        enabled: true
        servieName: ${spring.appliction.name}
        appName: weathermap
        # address: http://127.0.0.1:30100
        address: https://cse.cn-north-1.myhuaweicloud.com
      config:
        serverAddr: https://cse.cn-north-1.myhuaweicloud.com
        # serverAddr: http://127.0.0.1:30113
servicecomb:
  matchGroup:
    getWeather: |
      matches:
        - apiPath:
            prefix: "/weather"
  retry:
    getWeather: |
      maxAttempts: 5
      retryOnResponseStatus: 502
      waitDuration: 1000